
package imagesteg;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();

        setWindowInFullScreen();

        getContentPane().setBackground(Color.BLACK);
    }

    public final void setWindowInFullScreen() {
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();

        setSize((int) size.getWidth(), (int) size.getHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBarOperations = new javax.swing.JMenuBar();
        menuOperation = new javax.swing.JMenu();
        menuitemAudioMessage = new javax.swing.JMenuItem();
        menuItemExtract = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        menuitemExit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuItemProjectInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesteg/images/steg.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        menuOperation.setText("Action");
        
        /*
        menuItemExtract.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExtract.setText("Extract Message");
        menuItemExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExtractActionPerformed(evt);
            }
        });
        menuOperation.add(menuItemExtract);
        
*/
        
        menuitemAudioMessage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuitemAudioMessage.setText("Audio Message");
        menuitemAudioMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemAudioMessageActionPerformed(evt);
            }
        });
        menuOperation.add(menuitemAudioMessage);

        menuOperation.add(jSeparator1);
        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setText("Advanced stegenography");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        menuOperation.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem2.setText("visual cryptography");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        menuOperation.add(jCheckBoxMenuItem2);
/*
        menuitemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menuitemExit.setText("Exit");
        menuitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemExitActionPerformed(evt);
            }
        });
        menuOperation.add(menuitemExit);
*/
        menuBarOperations.add(menuOperation);

        menuAbout.setText("  About  ");

        menuItemProjectInfo.setText("Project Info");
        menuItemProjectInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProjectInfoActionPerformed(evt);
            }
        });
        menuAbout.add(menuItemProjectInfo);

        menuBarOperations.add(menuAbout);

        setJMenuBar(menuBarOperations);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemAudioMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemEmbedMessageActionPerformed
        new DHMain(this, true).setVisible(true);
    }//GEN-LAST:event_menuitemEmbedMessageActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
      VisualCryptography k=new VisualCryptography();
      k.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void menuItemProjectInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProjectInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemProjectInfoActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
  
        SecretInterface in=new SecretInterface();
      in.setVisible(true);
           // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println("Invalid look and feel : " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("Invalid class : " + e.getMessage());
        } catch (InstantiationException e) {
            System.out.println("Error in creating look and feel : " + e.getMessage());
        } catch (IllegalAccessException e) {
            System.out.println("Illegal : " + e.getMessage());
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBarOperations;
    private javax.swing.JMenuItem menuItemExtract;
    private javax.swing.JMenuItem menuItemProjectInfo;
    private javax.swing.JMenu menuOperation;
    private javax.swing.JMenuItem menuitemAudioMessage;
    private javax.swing.JMenuItem menuitemExit;
    // End of variables declaration//GEN-END:variables

    private void chooseFile() {
    }
}
